---

- name: Создаём директорию для данных backend
  file:
    path: "{{ remote_path }}/v2rs/backend/data"
    state: directory
    owner: "10001"
    group: "10001"
    mode: '0775'

- name: Генерируем секцию backend для config.yml
  template:
    src: config.yml.j2
    dest: "{{ remote_path }}/v2rs/backend/config.yml"
    mode: '0644'
