---

- name: Синхронизация статических файлов и директорий
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ remote_path }}/v2rs/subscription/"
    mode: '0755'
  loop:
    - assets
    - templates

- name: Генерируем секцию subscription для config.yml
  template:
    src: config.yml.j2
    dest: "{{ remote_path }}/v2rs/subscription/config.yml"
    mode: '0644'

- name: Копирование файлов singbox и mihomo
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ remote_path }}/v2rs/subscription/templates/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'templates/singbox/advanced/config.json.j2', dest: 'singbox/advanced/config.json' }
    - { src: 'templates/mihomo/advanced/base.yml.j2', dest: 'mihomo/advanced/base.yaml' }
    - { src: 'templates/mihomo/advanced/config.yml.j2', dest: 'mihomo/advanced/config.yml' }
    - { src: 'templates/xray/advanced/config.json.j2', dest: 'xray/advanced/config.json' }
    - { src: 'templates/xray/base/config.base.j2', dest: 'xray/base/config.base' }
