---

- name: Синхронизация статических файлов (assets)
  ansible.builtin.copy:
    src: assets
    dest: "{{ remote_path }}/v2rs/subscription/"
    mode: '0755'

- name: Создаём директорию для subscription
  ansible.builtin.file:
    path: "{{ remote_path }}/v2rs/subscription/templates"
    state: directory
    mode: '0755'

- name: Создаем структуру директорий для шаблонов подписки
  ansible.builtin.file:
    path: "{{ remote_path }}/v2rs/subscription/templates/{{ item.path }}"
    state: directory
    mode: '0755'
  with_filetree: "templates/templates"
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"

- name: Рекурсивно копируем и обрабатываем файлы шаблонов
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ remote_path }}/v2rs/subscription/templates/{{ item.path }}"
    mode: '0644'
  with_filetree: "templates/templates"
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"

- name: Генерируем секцию subscription для config.yml
  template:
    src: config.yml.j2
    dest: "{{ remote_path }}/v2rs/subscription/config.yml"
    mode: '0644'
