- name: Создаём директорию для subscription
  file:
    path: "{{ remote_path }}/v2rs/subscription"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Создаём директории для шаблонов подписки
  file:
    path: "{{ remote_path }}/v2rs/subscription/templates/{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - xray/base
    - xray/advanced
    - singbox/base
    - singbox/advanced
    - mihomo/base
    - mihomo/advanced

- name: Генерируем секцию subscription для config.yaml
  template:
    src: config.yml.j2
    dest: "{{ remote_path }}/v2rs/subscription/config.yml"
    mode: '0644'
