---
- set_fact:
    main_user_uuid: "{{ 999999 | random | to_uuid }}"

- name: Include all Docker app services
  include_tasks: "{{ item }}/main.yml"
  loop:
    - certbot
    - haproxy
    - nginx
    - xray
    - warp
    - deploy
