---
- name: Create base directories
  file:
    path: "{{ remote_path }}/certbot"
    state: directory
    mode: '0755'

- name: Copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ remote_path }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: entrypoint.sh.j2, dest: "certbot/entrypoint.sh", mode: '0755' }
    - { src: cloudflare.ini.j2, dest: "certbot/cloudflare.ini", mode: '0600' }
