- name: Создаём директорию для node
  file:
    path: "{{ remote_path }}/v2rs/node"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Генерируем секцию node для config.yaml
  template:
    src: config.yml.j2
    dest: "{{ remote_path }}/v2rs/node/config.yml"
    mode: '0644'
