---
- name: Bootstrap â€” install python3 and python3-apt (Debian/Ubuntu only)
  ansible.builtin.raw: >
    apt update -qq &&
    apt install -y -qq python3-minimal python3-apt
  when: ansible_os_family == "Debian"
  changed_when: false
  tags: always

- name: Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install basic packages (Debian)
  ansible.builtin.apt:
    name: "{{ common_packages_debian }}"
    state: present
  when: ansible_os_family == 'Debian'
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install basic packages (RHEL)
  ansible.builtin.dnf:
    name: "{{ common_packages_rhel }}"
    state: present
  when: ansible_os_family == 'RedHat'
