---
- name: restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted

- name: restart dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: restarted
